spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/DISS_DB
    username: postgres
    password: 123Andrei
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
