spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/mentormatch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
