spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/diss_db
    username: postgres
    password: 123Andrei
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  #to run the seeder again change this to 'create' and after the first run switch it back to update
    show-sql: true      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    